### ISSUE TITLE
Issue on page: Overview page example

### ISSUE THREAD

**Issue by ziadbkh** [ELIXIR-Belgium/elixir-toolkit-theme#196]
I would like to report an issue on the Overview page example page at `/overview_tiles`. Description of the issue:
How tiles are being sorted? is there any way to have a custom order of the tiles on the page? 
Thanks

**Comment by bedroesb** [comment]
The tiles are being sorted alphabetically and currently there is no way in doing it differently. Did you have a way in mind in how one could have a custom order? Currently the tiles are being generated by loping over all pages (which Jekyll does incrementally through the file structure in alphabetical order).

**Comment by ziadbkh** [comment]
A quick thought is to have an attribute in the page metadata to reflect the order. Might get tricky if the same page appears in different lists and needs to have a different order! 
 Or having like a page id that can be listed in the include statement in a specific order: for example 
 {% include section-navigation-tiles.html type="example_pages" order = "1,3,5,7" %} where the numbers in the order list are the page id .. 
 
 it needs more thinking for a general solution!

**Comment by bedroesb** [comment]
I like your proposal with the page_ids the most.

I am wondering if we still need the parameter `type` if people list specific page_ids. Maybe we let people make overview tiles through a `type` + through a `order`.

**Comment by bedroesb** [comment]
I recently moved the overview tiles to the `website section` page, but if you can make overview tiles not based on a type/section, I might want to rethink the documentation: https://elixir-belgium.github.io/elixir-toolkit-theme/website_sections

**Comment by ziadbkh** [comment]
I think listing the page ids as a way to filter and then sort is more comprehensive than just the type. it allows you to create a mixed list in case for whatever reason the same page needs to be in multiple lists. the filtration based on the type is easier as no need to do a list!

**Comment by bedroesb** [comment]
I think we can look at how currently contributor tiles are configured: https://elixir-belgium.github.io/elixir-toolkit-theme/contributors#list-website-contributors-in-a-grid
```yaml
custom: ', ' separated list of contributor names if you only want to show a specific collection of contributors.
role: specify the role of the contributors you want to filter on. This is not combinable with the custom list of contributors.
sort: disable sorting of contributors by adding false. Default: true.
col: give an integer to specify the number of columns/contributor cards per row. Default: 5.
```

Where role is in this case type. Here one can list individual contributors or specify a role, and separate decide whether it is sorted or not. I like the idea of having a similar mechanic here,
